### ISSUE TITLE
Design how to deploy an API built with FastAPI

### ISSUE THREAD

**Issue by achab** [Amenokal-Labs/legal-ai-assistant#29]

**Comment by romaissaMe** [comment]
I found those websites:
Render https://render.com
Railway https://railway.app
Cyclic https://cyclic.sh

- I assume we have to deploy only app folder
- the environment variables can be added as secret
- dependencies will be uploaded using requirements.txt but I ignore how to run python -m spacy download en_core_web_lg in the free mode since it's not in requirements.txt
@achab

**Comment by achab** [comment]
Ok, thanks for researching this. This SO post seems to be helpful for spacy model: https://stackoverflow.com/questions/61702357/how-to-add-a-spacy-model-to-a-requirements-txt-file.

**Comment by achab** [comment]
Now than we can install spacy model using requirements.txt file, let's deploy the API on Render.
